fix - try to start new branch with correct name
Difirton/java-filmorate pull request #3
Opened 2022-08-01 06:11 UTC by Difirton

2022-08-01 06:52 UTC, Difirton commented
У меня выдалось веселое воскресенье: в Windows была ошибка в реестре, из-за нее Idea тупила. Все компилируется и работает нормально, но после загрузки в git репозиторий,  git начинал проверку и валился на проверке, говоря, что невозможно выполнить fetch ветки. Моя проблема оказалась эксклюзивной. Я до 4 страницы гугла еще никогда не доходил=)) Хорошо, что догадался на другом компе попробовать открыть новую ветку и запушить все обновления.

2022-08-02 09:05 UTC, Frilock requested changes
Один комментарий с pom файлом, где надо поправить. Остальное все здорово, чувствую следующую итерацию работы можно будет не смотреть =))

2022-08-02 09:05 UTC, Frilock commented on pom.xml
> +			<version>2.13.3</version>
Версии артефактов нужно писать в properties. Pom файлы бывают очень больших размеров (и в проекте может быть не один pom файл), поэтому при обновлении версии очень легко запутаться и совершить ошибку (обновить не там или где то обновить, а где то нет). Поэтому правильнее писать все версии в properties по аналогии с версией Java. А тут делать так <version>${jacson.version}</version>

Это относится ко всем зависимостям.

2022-08-02 09:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@PathVariable("id") Long id,
В одну строчку аргументы влезают =) Не вижу смысла переносить

2022-08-02 09:05 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/config/validator/AfterDateValidator.java
> +    int day;
А тут не нужны модификаторы?

2022-08-02 15:30 UTC, Difirton commented on pom.xml
> +			<version>2.13.3</version>
Да, я хотел не забыть это сделать еще неделю назад до того, как дали проект и забыл.=)

2022-08-02 15:30 UTC, Difirton commented on src/main/java/ru/yandex/practicum/filmorate/config/validator/AfterDateValidator.java
> +    int day;
Нужны, на радостях, что валидация заработала забыл добавить.=)

2022-08-03 09:56 UTC, Frilock approved these changes
Принято

2022-08-03 09:56 UTC, Frilock commented on pom.xml
> +		<version>2.7.2</version>
А Spring чего не вынесли?)

2022-08-07 07:49 UTC, merged